### ISSUE TITLE
./configure fails on line 13459: Syntax error: Bad substitution

### ISSUE THREAD

**Issue by asmithrsa** [phabrics/nme#1]
I'm trying to install tme-0.12rc11 on NetBSD 9.2. Error happens after "checking for net/bpf.h... yes"

**Comment by phabrics** [comment]
This issue has now been fixed in the latest commit. The problem was how the case of a shell variable was being converted from lower to upper case. It was using the Bash syntax ${foo^^} to do it. Now it uses the tr command to do it more portably across other shells like ksh, zsh, etc.

You can either check out the latest version or look at the diff to make the change to your configure.ac, then do autoreconf -fi to regenerate configure before running it. Alternatively, if you have bash installed, you can run "bash ./configure" or similar. Note that you will also have to use gmake instead of make for now. 

Thanks and let me know if it works or if you need more help!

**Comment by asmithrsa** [comment]
Thank you for the quick reply and fix. I actually do have a couple of questions. What would be the best way of reaching out?

**Comment by phabrics** [comment]
If you have a specific question, I think it's probably fine to submit it as an issue here. You can also use the Project Page on OSDN (https://osdn.net/projects/nme/simple/) under Communication->Open Discussion. I don't see a similar functionality here on GitHub unless I missed it. You can also e-mail me directly at phabrics@phabrics.com if you don't want to post publicly.
